### ISSUE TITLE
modify the equipment list document

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#10]

**Comment by rehamelirani** [comment]
also can you please remove the model column from the equipment list?

that is,

i will only have the name of the equip ( arabic & english ) + its number (
Quantity)

Thanks in advance,



*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by rehamelirani** [comment]
what is the code that i have to plug to my website??
and btw, what link shall i copy when i modify the list??




*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by pro-freelancer** [comment]
This is the demo
http://www.pro-solutions.net/customcms/index.php/tables/get_table/11

this is how it will look on the website once embedded.
http://pro-freelancer.github.io/yamenest/equipments.html

and this is the code you should implement to your website:
```
<p><iframe src="http://www.pro-solutions.net/customcms/index.php/tables/get_table/11" style="width:100%;height:1100px;border:none;" scrolling="no" ></iframe></p>

```

PS: The table model back end is working 100% with all exceptions and features. I will add the arabic main titles for 2 or 3 tables max, kindly modify at the end of the table of equipments the arabic title, check them from the document and copy past as a try of the back office from your part. In case any error reply to fix.

Also all embeded pages are the same code above you replace the src url code into following link pattern. http://www.pro-solutions.net/customcms/index.php/tables/get_table/11 11 as example is the bale id of the equipment that you can find from the backoffice, if you need to get the current table you put 1 instead of 11 and so on, try the url by changing the id's you find from table list at the back office and you will get the tables .

This is it, Video module and Table Module are done, any feedback is appreciated..
This ticket is closed.
