### ISSUE TITLE
Demo page for video youtube yamenest section

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#2]
Create a demo on how it will look.

**Comment by pro-freelancer** [comment]
I implement the needed code, and will close it tonight by sending you a demo link

**Comment by pro-freelancer** [comment]
This is how it will looks.

http://pro-freelancer.github.io/yamenest/

Your freedback is appreciated.

**Comment by rehamelirani** [comment]
hello Fadi,

this is is nice.
Yet, i would like to have one tiny modification.

Please find attached document.

Best,



*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by pro-freelancer** [comment]
This issue was reopened to work on the video request changes and send you a demo link and the code to embed if it passed to the website.

**Comment by pro-freelancer** [comment]
this is the demo link:
http://pro-freelancer.github.io/yamenest/

this is the code to emebed:
```
<iframe width="366" style="width:100%; height:3000px;border:none"  scrolling="no" src="http://pro-freelancer.github.io/yamenest/youtube/index.html"></iframe>
```

PS: you should replace all the content in the video page by this Iframe code so it will work properlly.

This issue is closed.

**Comment by rehamelirani** [comment]
one more concern,

what if i wanted to add additional videos in the future?
what will be the procedure ?




*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by pro-freelancer** [comment]
You go to youtube and add as many videos you want, and all you have to do in your backoffice the height:800px you increased till it show all the content. That it . aproximatelly you add 200px each video, you will discover the correct value by practice :+1:

**Comment by pro-freelancer** [comment]
I took a backup of the current vidoes section of the website. In case you like to revert to the old content someday it is possible with github.
this is the link of the old videos section backup.
http://pro-freelancer.github.io/yamenest/backup/videos/

**Comment by rehamelirani** [comment]
okay, i loved the edited video page!

however the thing is the video page created on my website does not work as
the rest articles!
They made in a way that you to their template, you click add video tab,
type the url, and the video will be directly downloaded in the video
section.

That is i do not have a separate article for video to apply the code as in
the career page and others.




*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by pro-freelancer** [comment]
Then you need to change the type of the video menu from opening a video to an article type.
I think you need to create a new article you name it videos, add the code , then link the video menu to this article. In case you have no clue in how doing it and you don't have any support from the site creator, kindly send me the credentials I will figure it out and implement the video for you.

**Comment by rehamelirani** [comment]
yes i prefer that when you come to apply such changes.

i requested to remove the model column from equipment and i had to reply.
can please remove it?




*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by pro-freelancer** [comment]
sure will do and send you feedback in the comming 24 hours once done.

**Comment by pro-freelancer** [comment]
will be implemented on sunday at the meeting.
