### ISSUE TITLE
one of the records are missing while navigating in the front end

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#20]
check why it is missing.

**Comment by pro-freelancer** [comment]
this is the preview of the current projects.
http://www.pro-solutions.net/customcms/index.php/tables/get_table/1

**Comment by pro-freelancer** [comment]
This is the preview of the factory projects
http://www.pro-solutions.net/customcms/index.php/tables/get_table/11

Still need to fix the font and will send you the new link to embed and close this issue, kindly check the content if correct for now.

**Comment by rehamelirani** [comment]
Hollow blocks is wrong!
the main title shall contain underneath two sub titles.

same goes for Asphalt batching plant! the main title shall contain a sub
title underneath !
if you check what is written under the main title you will realize that
u've added nothing but copied paste the title itself!

same for the sand washing pant!

remove sand washing plant from concrete machinery!

KINDLY RE-CHECK THE ATTACHED DOCUMENT AND MODIFY THE EQUIPMENT LIST!!

thanks in advane






*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by rehamelirani** [comment]
there are so many missing things from the table!
please re-check the document sent and modify accordingly.



*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by rehamelirani** [comment]
the current projects is now correct. thanks.
however, why the syndicate of engineers image is not seen?
as i remember, i've downloaded it.

did you manage the issue regarding moving fields?!
because i might be changing its order.





*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by pro-freelancer** [comment]
I opend a ticket for the moving fields it is related to the back office, Now I'm finishing the front end display. Once done will fix the remaining priority opned tickets bugs and close them, you will be posted.

**Comment by pro-freelancer** [comment]
This is the current projects how it looks .
http://pro-freelancer.github.io/yamenest/current_projects.html?new#.VTWXSSe1Gkp

this is the embeded code
```
<iframe src="http://www.pro-solutions.net/customcms/index.php/tables/get_table/1" style="width:100%;height:1000px;border:none;overflow:hidden" scrolling="no" ></iframe>
```

This is the factory projects how it looks
```
http://pro-freelancer.github.io/yamenest/equipments.html?new#.VTWYaye1Gkr
```

The embeded code:
```
<iframe src="http://www.pro-solutions.net/customcms/index.php/tables/get_table/11" style="width:100%;height:1100px;border:none;overflow:" scrolling="no" ></iframe>
```

I just fixed the back office main issues, and some of the display of the equipment projects, as I remembered you changes the display of the list by minimizing the records of this table.
Kindly test the backoffice by adding the removed images as by checking and filling the missed content.

Send me feedback if any errror occured, as I will manage to make the Enhancements issues in the coming days.

**Comment by rehamelirani** [comment]
WHERE IS THE PIC COLUMN for the equip list ???

and i did not like the errow  thing !
and table words size, font, and even the column and row difference is not
the same!!
fix it please!





*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by rehamelirani** [comment]
+ both tables looks too big on their corresponding pages !
make them coherent in terms of size.



*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by pro-freelancer** [comment]
Well received , will check them tonight and reply back. Regards.

**Comment by rehamelirani** [comment]
what is done?

you are not replying on  my emails.
you opened the issues and closed them and i do not any more know what are
you doing.

Did you modify the equipment list ? as provided in the attachment?
Did you make their size coherant with the website?
did you make sure that word's size, columns, and rows are all of same size??
Did you remove the two big arrows and put instead number of pages??

may i publish them online???




*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by pro-freelancer** [comment]
You can't reply that way....
It was my responsibility to make a working system for you ,
as a developer I fixed all issues related to my responsibility.

your responsibility is to test the system and add the content , cause by nature it is not in the scope of   our deal.
Even that I was gentle enough with you and took the initiative to help you out on adding all the content and I'm trying my best to finish this the soonest.

So what is done is:
1- you can add as many record (the bug was fixed).
2- you can move record between table to other (this was fixed)
2- a new table display that makes sure is displaying all content (this was fixed)

since many features was added to the back office such a WYSWYG Editor wish literally changed the display of the the front end font and size, and since some modifications was made to the front end to display properly the content, this lead to small issues on the design that can be fixed easily .
as I replied before, I will check these small issues tonight and reply back with a fix.

you can publish the one you see is correct such current projects
http://pro-freelancer.github.io/yamenest/current_projects.html?new#.VTWXSSe1Gkp

in case you like to fix the layout before publishing them, so don't publish them before you are satisfied of the output.
I already send you a snap shot of how they will shows before publishing them, and you replied with some comments that I should fix tonight.

I'm not asking more than to have a respectful level of communication. 

Regards,

**Comment by rehamelirani** [comment]
Oh my God ! I did not mean to disrespect you! Not my intentions at all. 

M sorry about that anyways! 

The thing is, ive sent you a private email asking u about the modifications  and u never replied. That is why sent i sent it as reply on a closed issue for your to notice it! Nothing more nothing less! 

As for the equipment table, you have same names for both the main title and subtitlesI do not know which to remove and which to keep knowing that last Sunday i fixed them when u were trying to fix other issues and all were correct! I don't know what happened when u sent me the code and why the appeared wrong! That is why i asked u to fix it ! That is why ive resend you the attachment for you to check in case there is something wrong in the system of the equip table! 

There is nothing personal!
I respect you and your work regardless of your time issues!

**Comment by pro-freelancer** [comment]
OK no problem, sorry for that anyway :)

Will focus on them tonight, and it is my fault not replying after I finish the work on a final report from email and not git hub..

Git hub will send you notifications on anything I write, and sometimes I write technical things that is necessary for personal notes to remember the history of the project and continue accordingly. 

Will be aware on that ;)
as I will work tonight , yesterday I didn't have the chance .

Regards,

**Comment by pro-freelancer** [comment]
I will close this ticket
