### ISSUE TITLE
Did you modify the equipment list ? as provided in the attachment?

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#27]
I'm checking it now, and reply once done.

**Comment by pro-freelancer** [comment]
this is a correct final demo.
http://pro-freelancer.github.io/yamenest/equipments.html#.VThMyye1Gkr

Asphalt Batcher was corrected by adding the correct field.
checking evrething is correct, 4 missing transportation facilities was added (Siyarat siyahiya)
This issue is closed.
if you liked the demos you can embed, if not any feedback is appreciated.
PS: the back office is working 100% once I modified and moved tables and all current features are working. the remaining tickets are enhancements and not priority that will be closed with time.
Regards,

**Comment by rehamelirani** [comment]
hello fadi,

no i am trying to update it however i am confused with the main title and
subtitle in the table and i am not being able to sort them the way i want
in order to be able to know what am deleting and modifying.

kindly remove all siyarat seyaheya i dont want to put them.

and show me how i can see the table as it appears, or something like that
 to facilitate editing and modifications.

Best,





*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by rehamelirani** [comment]
one more thing,

when implementing the table on website, can you lower the table from the
words already existing above it?

+ I do not what the errow things, i don't like there place.

also, can you allow the the rows/table to be seen the same as you through
other pages.
for instance the equip list first page contains more rows than that of the
second page.
i want it to be the same.

thanks




*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com

**Comment by pro-freelancer** [comment]
Will try to figure it out tonight, what concerns the arrows, I'm using other plugin than the old bullets navigation, this one is more guaranteed to display all records and more flexible . So will check if possible to change the behavior of an arrow but I'm not sure. What concerns to have same size, I will try to do it tonight.

Regards,

**Comment by pro-freelancer** [comment]
uppon your request both display tables are fixed, removed the navigation arrows and put the old bullets at the bottom, making sure that each 10 records will stop the page and continue on the next. these are the demos:
http://pro-freelancer.github.io/yamenest/current_projects.html?refresh=10

http://pro-freelancer.github.io/yamenest/equipments.html?refresh=15#.VTqmySe1Gkq

to embed:
current projects:
```
<iframe src="http://www.pro-solutions.net/customcms/index.php/tables/get_table/1" style="width:100%;height:700px;border:none;overflow:hidden" scrolling="no" ></iframe>
```

equipments:
```
<iframe src="http://www.pro-solutions.net/customcms/index.php/tables/get_table/11" style="width:100%;height:600px;border:none;overflow:" scrolling="no" ></iframe>
```

Tomorrow will visit your office between 10 to 11 pm.

Regards,

**Comment by rehamelirani** [comment]
Many thanks fadi.

I will check them online tomorrow morning cz i do not have my laptop right
now.

Thanks.
