### ISSUE TITLE
Priorities for 30 May

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#32]
1- remove title from the tables(header title).
2-picture to be single picture in multiple row.

**Comment by pro-freelancer** [comment]
things to do:
1- career page on facebook tab. ( I need the credentials of the yamen facebook page to implement).put as admin for a limited time.
2- start working on the campaign by creating a status report on how yamen is ranked in the SEO and put your suggestions.
3- start working on the fixes tables and finish at least 3 bugs issues for this month.

**Comment by pro-freelancer** [comment]
Sunday May 31, Start working on the current issue, and the title from the tables(header title) was removed successfully.

**Comment by pro-freelancer** [comment]
Dear Reham, I worked on the career page for facebook page.
you can find a demo here.
https://www.facebook.com/ProFreelancer79/app_208195102528120

in case you need to implement it on yourpage.
Kindly add me as an admin on your page facebook name (Fadi Nicolas Zahhar) so I can implement it to your page.

Regards,

**Comment by rehamelirani** [comment]
and you are now an admin on Yamen Est.


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by rehamelirani** [comment]
Greetings Fadi,

Can i Add what is written on the website in my career page?
because having the tab does not really grab attention and the page will
look empty.

" At Yamen, we are completely devoted to recruiting and retaining the
premium talent to encounter and surpass the requirements of all our
business units and customer’s requests.

Why Yamen?

Yamen provides a healthy work environment for its valued employees, free
from flows and disruption in order to invest the best out of their
capabilities.

We pride ourselves on possessing a culture that gives everyone the
opportunity to shape their future of success to reach higher levels of
professionalism.

Presume a range of challenges and prospects to stretch your practical and
technical skills to better develop an extra-ordinary experience at Yamen. "

what do u think?




*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
OK, will do a seperate page and add the content for it. will let you know once done.
Regards,

**Comment by pro-freelancer** [comment]
The page was successfully implemented.
https://www.facebook.com/pages/Yamen-est/1401615990108119?sk=app_208195102528120

in case you sow a panel at the top with a settings, please don't let your curiosity in entering this section.  You may corrupt the settings of the page.
This settings shows only for administrators, regular people will not see this.

you can sign out on facebook and check the link you will see how regular people will see your page.

PS: I will send you suggestions that can be added on yamenest facebook page with implementation list price so you can choose from.
The career page was on the house alternative to the broken youtube video code .

Regards

**Comment by pro-freelancer** [comment]
List of ideas :+1: 

simple divided into 2 ideas:

1st the previous tables modules, can be implemented with a facebook tab page (single page) that you can choose what type of info you need to get like current projects, and materials and so on... (same tables on the website with better user experiance) (implementation cost 300$ as a final price)

2nd: a single page design that introduce yamen projects, gallery and so on, technically they name it as mini-sites, a mini site is a single long page that have many section that introduce a company most important data such about the company, some of the project, contact us form and so on:
I have some pre-made template for sale I will put the links below. the cost of such mini site as a final price 500$ that will be dynamically modified from the customcms that you already use.
examples that you can chose from :+1: 

http://www.pro-freelancer.info/ready_templates/creativepix/
http://www.pro-freelancer.info/ready_templates/trial/
http://www.wood4design.com/
http://www.pro-freelancer.info/ready_templates/umbrella/

http://www.pro-freelancer.info/ready_templates/first/
http://www.pro-freelancer.info/ready_templates/second/
http://www.pro-freelancer.info/ready_templates/third/
http://www.pro-freelancer.info/ready_templates/forth/
http://www.pro-freelancer.info/ready_templates/fifth/

always you can choose more than theme (tab page) for many marketing purposes depends on your services diversification and audience targeting .
PS: the themes are adjustable to fit yamen colors and logo
Regards,

**Comment by rehamelirani** [comment]
Yes i saw it but did not click on it :)

Thank you,
it looks nice.

Where will be the cvs sent to ? same as the website?

Best,



*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
yes it is a replica module of the website... are we on a meeting for tomorrow, and what about the Ideas I send!? anything interesting !!!? Regards,

**Comment by rehamelirani** [comment]
yes we will have a meeting tomorrow, same time, 10 am.

will tackle the ideas tomorrow.

Best,



*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
This ticket is closed due for the possibility to work on the SEO as facebook app was rejected. No need for this ticket anymore.
