### ISSUE TITLE
Mobile responsive for tables

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#33]

**Comment by pro-freelancer** [comment]
As you can see on this link, if you minimize and maximize the window, the table is responsive.
http://www.pro-solutions.net/customcms/index.php/tables/get_table/1

to fix it on the mobile while you putting the iframe make sure that the width of the iframe is 100% 
```
iframe width="100%"
```
this issue is closed.

**Comment by rehamelirani** [comment]
I've implemented it online however the bullets underneath the table are
inside it.
lower the number of rows by 2 having a total number of 12 rows. i believe
after that the issue will be closed.

thanks in advance


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by rehamelirani** [comment]
yes i've check it for the current  and equipment table and it works on
mobile.
thanks


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
ok this ticket is closed since I fix it yesterday.
