### ISSUE TITLE
Table content modification

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#34]
since most of the current table has to be modified, i've sent it all in order to compare with what is present and what has to be added.
mainly " majles aljanoub" part is deleted, and additonal fields and modifications were applied to " Wezarat Al-Shghal L 3ama "

**Comment by pro-freelancer** [comment]
Kindly check the updated table.
'''
http://www.pro-solutions.net/customcms/index.php/tables/get_table/1
'''

you can put it online by adding the Iframe now.

**Comment by rehamelirani** [comment]
thanks.

However, when trying to modify position of projects in  majles l janoub,
the entire section related to majles l janoub is removed.

and some projects are written but not seen online - as Construction of
additional annex for Nabatieh's Public School - in Majles Al-Janoub.

+ there is one missing project in wezaret al-ashghal which is Construction
of Serial Nabatieh - أشغال بناء سراي النبطية الحكومي الجديد



*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
will investigate, as I just added the tables, no fixes was implemented for the current code. this will be improved shortly. thanks for your feedback.

**Comment by pro-freelancer** [comment]
Kindly check the table if correct.
http://www.pro-solutions.net/customcms/index.php/tables/get_table/1

While using a real demo data management, I'm not satisfied from the user experience. I admit that the system is a major painful frustrating experience and need improvments. 

for now just send me all your changes that I will do them. 
I will upgrade the user interface as follow demo .
http://www.shopdev.co.uk/blog/sortables.html

so you can be able to order the fields in a click of a button.

your feedback is appreciated on the table, in case is correct you can add it to your website.

Regards

**Comment by pro-freelancer** [comment]
Enhancement of the table to be logically displayed upon the frame height.

**Comment by pro-freelancer** [comment]
The current table was fixed only. you can add it to the website.
Each table have it's own specification code.
current table was fixed, you need to give me other tables to be able to test and fix.
Also there is a plan to enhance the back office to make it easy for modifications.

Regards,

**Comment by rehamelirani** [comment]
as per your request, Kindly find attached tables for construction,
electrical, roads, and water.
when you complete your check up on their fixes, i would like to make them
online on my website.

as previously agreed, you can remove the image column from the above
mentioned tables.

i will leave the image column for equipments and current tables only.

once done let me know to check them.

thanks.


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
Dear Reham,
Kindly send me the files on info@fnz.me
you can't attached a document on github reply, you can only put a url of
dropbox.

Regards,
