### ISSUE TITLE
Investigating 

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#36]
1. water and waste water projects online
2. Uploading images from the back office

**Comment by pro-freelancer** [comment]
remember the image should be jpg for web format as no spaces in the name of the image.

**Comment by rehamelirani** [comment]
okay, well noted.

Thanks


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>
