### ISSUE TITLE
 the current project table and equipment list to include images. 

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#37]
Planing to refactor the code to have a horizontal scrolling effect instead of vertical scroll, same look and feel, In this case will make sure that the height of the table is unique even it includes images or no images, cause the effect will be based on the height of the page and not on the section....

also the quentity will be back as old version. 
Once the modifications are done will send you a link to see the results.

**Comment by pro-freelancer** [comment]
After some studies, the best solution to fix the display table problem of equipment table that will be adopted the same for current projects. is to allow you to put a break point = 1 from the backoffice. so You will have the flexibility in telling where each page ends. So you will have controle on how the list will display correctly. 

Now fixing the quantity to close this issue. in minutes.

**Comment by pro-freelancer** [comment]
What concerns the images, the upload process is working fine, the format you were uploading is PNG. the system only accept jpg for web as you should name the picture with no space, the space could corrupt the images.

**Comment by pro-freelancer** [comment]
You can check the website , all tables are displayed correctly using the new breakpoint feature, the electrical tables you should add the code and do the break point by adding one, or just add it to finish it the soonest and close this module.

**Comment by rehamelirani** [comment]
Dear Fadi,

Thank you.

However what do you mean by break point? what should i add to the code. I'm
still working and fixing it in the back office prior to putting it online.

Also, one more thing ( hopefully the last one ), regarding the water
projects, where i have "*اشغال لصالح وزارة الطاقة والمياه - مؤسسة مياه
لبنان الجنوبي"*

 the corresponding projects are displayed having blue line separating each,
as :
[image: Inline image 1]

i've tried to move them be under the client; yet, did not find its name.
Can you please fix them? or show me how and i will do it.
Kindly find attached project list for the above mention client.


Thanks in advance,
Best,



*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by rehamelirani** [comment]
Dear Fadi,

I was fixing the electrical project list, however, today everything i've
been modifying ( in terms of words ) is not being modified and the system
is not taking it.

Besides, i've tried the link to check the electrical list prior to putting
it online, it has only displayed slide one. I've used the following link:
http://www.pro-solutions.net/customcms/index.php/tables/get_table/2

why so?

Thanks in-advance,
Best


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
Dear Reham,
This is normal.
The added feature breakpoint you see in the back office is the reason.
The breakpoint should be =1 on the row you need to break and to go to next page.
I will do an example for you now on the electracity table. Electrical work in Rmeich, I will edit it and add a break point. you will notice that it will break and go to the next page.

This solution is good that allowed you to break the pages as it fits you. 

check after I added a breakpoint = 1
```
http://www.pro-solutions.net/customcms/index.php/tables/get_table/2#firstSlide
```
Kindly continue the pattern in adding breakpoints before the points of the table.
Another hint that you should do alone and continue.  Electrical work in El- Bisarieh

Regards.

**Comment by pro-freelancer** [comment]
Also use chrome in the back office, don't use internet explorer or Firefox of any version. Thank you.

**Comment by pro-freelancer** [comment]
This was fixed.

```
http://www.yamenest.com/business/yamenest/pages/1622/Water%20Projects#.VcpxLPmqqkr

```

**Comment by pro-freelancer** [comment]
As a rooteen final test of the system. I did the following.

1. Added a new record. (succeed)
2. Removed the new Record (succeed).
3. Added the needed breakpoint for the electrical 
this is the link.
http://www.pro-solutions.net/customcms/index.php/tables/get_table/2

4. Tested the move of the previous water projects table (the move worked fine as I found the related destination by reading the full tile of english - arabic - second arabic title if exisest ) passed.

All remaining issues was tested and working as expected.
This module (Table module ) is complete No issue remaining for Version 1.0

**Comment by rehamelirani** [comment]
Thank you.


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by rehamelirani** [comment]
Okay.

one tiny problem, i've tried to break the page between:
[image: Inline image 1]

and it did not work out.
It was break 3

Best,
Reham



*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
I'm fixing them, you should only put 1 or 0 in the break point.
2 or 3 is incorect.

ps: once you put 1 it will go to next page. in case you need to remove it put 0

**Comment by pro-freelancer** [comment]
fixed them.

```
http://www.pro-solutions.net/customcms/index.php/tables/get_table/2

```

beaware in case you need to redo the break points, you should redo them page by page.
example, if you need to redo starting page 2. you should check page 3, 4, 5 till the end.

you need to remove the break points that follow page 2 by putting the value 0.
and put the correct break point row by putting the value 1.

I think the way it show now is good.

Regards,

**Comment by rehamelirani** [comment]
Thanks.

Just noticed the images on the equipment table. I want it as before. no
magnifier. and it does not open for the entire's table's length.
Please fix it.

Best,
Reham


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by rehamelirani** [comment]
Dear Fadi,

Can you please fix the images? and return it as it was??

I do not like this one:
[image: Inline image 1]

It extends to the entire table, and this does not look nice nor
professional.
Please re-do it as it was before.


Best,
Reham


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
Will fix it tomorrow .

**Comment by pro-freelancer** [comment]
Fixing the issue.

**Comment by pro-freelancer** [comment]
The issue was fixed.
Kindly note you need to replace the equipment code from the back office to the following.

```
<iframe style="width: 100%; height: 630px; border: none;" src="http://www.pro-solutions.net/customcms/index.php/tables/get_table/11" scrolling="no"></iframe>

```

this will allow to center the image while clicking.
This issue was fixed.

Also kindly note that the final support to this module will be to the end of August.
Other modifications or fixes will not be for free.
Regards,

**Comment by rehamelirani** [comment]
Dear Fadi,

I do not want the picture to change once scrolling the mouse.
Maybe the applicant is just scrolling to reach the picture, because as you
made it, it doesn't open in the middle of the table.

Best,


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by rehamelirani** [comment]
Also, please let the image ONLY appears, i do not like the grey part under
it.

[image: Inline image 1]


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
You didn't understand that for this module to work you need to replace the equipment code from the website equipment page.

you should add this .

```
<iframe style="width: 100%; height: 630px; border: none;" src="http://www.pro-solutions.net/customcms/index.php/tables/get_table/11" scrolling="no"></iframe>
```

will fix tonight the scroll image mouse issue. but you should replace the code above on the equipment page in your website back office

**Comment by rehamelirani** [comment]
It is the same code that i have implemented.

I did. and the grey part underneath the pic is still present.
[image: Inline image 1]

and the pic looks bigger than the table, can it be smaller?

Okay, Thanks.



*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
I test it online , it is working perfectly.
Kindly note that you should clear your cache to see the changes.

to check it correctly , open chrome browser, at the top right (click the nav button).
click new incognito window or (ctrl+shift+n).
paste the following url 
http://www.yamenest.com/business/yamenest/pages/1619/Equipment#.VdRH7fmqqko

you will notice that no caches is displayed and the design is correct.

**Comment by rehamelirani** [comment]
okay, this is what happened:
[image: Inline image 1]

Please, as previously mentioned, let the picture be smaller. i don't want
it to be larger than the table itself.

Thanks in advance,
Best,


*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
can you send the image on a new email send to info@fnz.me , I can't check it here on github.

Also, I think it is cool the way it is.
Waiting for your image attached to see what is your point of complaint ...

Regards

**Comment by pro-freelancer** [comment]
I do not want the picture to change once scrolling the mouse. Done.
Please, as previously mentioned, let the picture be smaller. i don't want
it to be larger than the table itself. Done.
Also removed the navigaiton so each picture opens independently.

All remaining issues are done, Kindly confirm that this module is closed.

**Comment by rehamelirani** [comment]
Yes, this is what i wanted.
Please make sure that the photos for the current table till appear as the
equipment table.

Thanks.

Best,



*Reham El IraniConstruction Manager*
*mobile: 00961 76 905205*



*Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For
Trading and Industry*        Head Office: Beirut - Airport Street - Resslan
Center - 1st floor     Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Office: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752 603
        Nabatieh Office: Mroue Center - 3rd floor     Tel: 00961 7 765600
Fax: 00961 7 765600
        Erbil Branch: Kurdistan - Aveen Street - Anikawa     Tel: 00964 750
1488824
        Concrete & Asphalt Batching Plants - Crushers - Sand Washing Plant
- Hollow Blocks & Asphalt Pursuant Factory
        Kfour Nabatieh     Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax:
00961 7 531533
        Website: www.yamenest.com    Emails: info@yamenest.com
yamen@yamenest.com  factories <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>   erbil <yamen@yamenest.com>@yamenest.com
<yamen@yamenest.com>

**Comment by pro-freelancer** [comment]
Well noted. Will replicate the code and close this module.
