### ISSUE TITLE
Update the layout for next previous page one page 2 like the old navigation

### ISSUE THREAD

**Issue by pro-freelancer** [pro-freelancer/yamenest#6]

**Comment by pro-freelancer** [comment]
Layout updated
```
<iframe src="http://www.pro-solutions.net/customcms/index.php/tables/get_table/1" style="width:100%;height:1000px;border:none;" scrolling="no" />
```

this is the code should be added

**Comment by rehamelirani** [comment]
kindly note that i was trying to upload pix beside each project for the
current table!
yet one i pressed remove pic - 404 Page not found - pops out!

so please fix it.

Thanks in advance,
Best,




*Reham El IraniCivil Engineer**mobile: 00961 76 905205*


Yamen Est. For General Trading and Contracting & Yamen S.A.R.L. For Trading
and Industry
        Head Office: Beirut - Airport Street - Resslan Center - 1st floor
  Tel: 00961 1 450629 Fax: 00961 1 450628
        Saida Branch: Dandachli Plaza - 4th floor     Tel: 00961 7 752601/2
Fax: 00961 7 752603
        Erbil Branch: Kurdistan: Aveen Street - Anikawa, Erbil     Tel:
00964 750 1488824
        Kfour Nabatieh: Concrete & Asphalt Batching Plants - Crushers -
Hollow Blocks & Prefabricated Bricks Factory
        Tel: 00961 7 531000 - 00961 7 531556/7/8 Fax: 00961 7 531533
        Website: www.yamenest.com     Emails: info@yamenest.com
yamen@yamenest.com
